[package]
name = "voting"
version = "0.1.0"
edition = "2021"

[dependencies]
odra = { workspace = true, default-features = false }
odra-modules = { workspace = true, default-features = false }
utils = { path = "../utils", default-features = false }
core_contracts = { path = "../core_contracts", default-features = false }
configuration = { path = "../configuration", default-features = false }

[features]
default = ["mock-vm"]
mock-vm = ["odra/mock-vm", "odra-modules/mock-vm", "utils/mock-vm", "core_contracts/mock-vm", "configuration/mock-vm"]
casper = ["odra/casper", "odra-modules/casper", "utils/casper", "core_contracts/casper", "configuration/casper"]
