[workspace]
members = [
    "bid_escrow",
    "core_contracts",
    "configuration",
    "modules",
    "utils",
    "voting",
    "voting_contracts",
]

[workspace.dependencies]
odra = { path = "../odra/odra/core" }
odra-modules = { path = "../odra/odra/modules" }

