[workspace]
members = [
    "dao",
    "macros",
]

[workspace.dependencies]
odra = { path = "../odra/odra/core", default-features = false }
odra-modules = { path = "../odra/odra/modules", default-features = false }

