[workspace]
members = [
    "dao_contracts",
    "dao_modules",
    "dao_utils"
]

[workspace.dependencies]

odra = { git = "https://github.com/odradev/odra.git", branch = "feature/derive-odra-type" }

