[[contracts]]
name = "variable_repository"
fqn = "dao::core_contracts::VariableRepository"

[[contracts]]
name = "admin"
fqn = "dao::voting_contracts::AdminContract"

[[contracts]]
name = "reputation_contract"
fqn = "dao::core_contracts::ReputationContract"

[[contracts]]
name = "reputation_voter_contract"
fqn = "dao::voting_contracts::ReputationVoterContract"

[[contracts]]
name = "va_nft_contract"
fqn = "dao::core_contracts::VaNftContract"
