[package]
name = "utils-contracts"
version = "0.1.0"
edition = "2021"

[dependencies]
odra = { workspace = true }
modules = { path = "../modules", default-features = false }

[features]
default = ["mock-vm"]
mock-vm = ["odra/mock-vm", "modules/mock-vm"]
casper = ["odra/casper", "modules/casper"]
